#!/bin/bash -ex

NODEUSER=node

su -lc "[[ "$FAB_HTTP_PROXY" ]] && export http_proxy=$FAB_HTTP_PROXY; cd /opt/tklweb-cp && npm i redis-commander" $NODEUSER
su -lc "[[ "$FAB_HTTP_PROXY" ]] && export http_proxy=$FAB_HTTP_PROXY; cd /opt/tklweb-cp && pm2 start ecosystem.config.js && sleep 20 && pm2 save && pm2 kill" $NODEUSER

rm /etc/nginx/sites-enabled/tkl-default
ln -s /etc/nginx/sites-available/redis /etc/nginx/sites-enabled/redis
